apiVersion: apps/v1
kind: Deployment
metadata:
  name: Hello_World_Application
spec:
  replicas: 3   # Adjust the number of replicas for high availability
  selector:
    matchLabels:
      app: Hello_World_Application
  template:
    metadata:
      labels:
        app: Hello_World_Application
    spec:
      containers:
      - name: hellocont
        image: helloworld 
        ports:
        - containerPort: 5000