apiVersion: v1
kind: Service
metadata:
  name: Hello_World_Application
spec:
  selector:
    app: Hello_World_Application
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer   
